-- AlterTable
ALTER TABLE "Users" ADD COLUMN "eventoId" INTEGER;
ALTER TABLE "Users" ADD COLUMN "hotelId" INTEGER;
ALTER TABLE "Users" ADD COLUMN "rg" TEXT;
ALTER TABLE "Users" ADD COLUMN "vooId" INTEGER;
