version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5431:5432
  api:
    depends_on:
      - db
    build: ./
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/home/app
      - /home/app/node_modules
